### ISSUE TITLE
Deploy should fail on FS errors

### ISSUE THREAD

**Issue by msoute** [msoute/vertx-deploy-tools#2]
org.vertx.java.core.file.FileSystemException: java.nio.file.AccessDeniedException: /var/www/mathplus/4.4/web/deferredjs/F2A6FCB081312C0D360230D02596DAA4/10.cache.js
	at org.vertx.java.core.file.impl.DefaultFileSystem$9.action(DefaultFileSystem.java:615) ~[vertx-core-2.1.2.jar:na]
	at org.vertx.java.core.file.impl.DefaultFileSystem$9.action(DefaultFileSystem.java:593) ~[vertx-core-2.1.2.jar:na]
	at org.vertx.java.core.file.impl.DefaultFileSystem.deleteSync(DefaultFileSystem.java:198) ~[vertx-core-2.1.2.jar:na]
	at nl.jpoint.vertx.mod.cluster.command.ExtractArtifact.execute(ExtractArtifact.java:47) ~[nl.jpoint.vertx-deploy-tools~vertx-deploy-mod~1.0.1.128/:na]
	at nl.jpoint.vertx.mod.cluster.service.DeployArtifactService.deploy(DeployArtifactService.java:53) ~[nl.jpoint.vertx-deploy-tools~vertx-deploy-mod~1.0.1.128/:na]
	at nl.jpoint.vertx.mod.cluster.handler.servicebus.DeployHandler.deployArtifacts(DeployHandler.java:79) ~[nl.jpoint.vertx-deploy-tools~vertx-deploy-mod~1.0.1.128/:na]
	at nl.jpoint.vertx.mod.cluster.handler.servicebus.DeployHandler.handle(DeployHandler.java:44) ~[nl.jpoint.vertx-deploy-tools~vertx-deploy-mod~1.0.1.128/:na]
	at nl.jpoint.vertx.mod.cluster.handler.servicebus.DeployHandler.handle(DeployHandler.java:17) ~[nl.jpoint.vertx-deploy-tools~vertx-deploy-mod~1.0.1.128/:na]
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951) ~[vertx-core-2.1.2.jar:na]
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175) [vertx-core-2.1.2.jar:na]
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175) [vertx-core-2.1.2.jar:na]
	at org.vertx.java.core.impl.OrderedExecutorFactory$OrderedExecutor$1.run(OrderedExecutorFactory.java:92) [vertx-core-2.1.2.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

**Comment by msoute** [comment]
Implemented since version 3.0.0
